/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:1e5e5d7f-5d77-4dcb-ae84-0c244de209cd",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_bqcnrbTBH",
    "aws_user_pools_web_client_id": "47009kkdrkkdlkc9jcikcc3voh",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://m4pngsglvvgzlg7owajrwhcok4.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-am7mjutwzraenpfswmx4eytzgi"
};


export default awsmobile;
